<!DOCTYPE html>
<html lang="en"><head>
<script src="Oct13_session1_files/libs/clipboard/clipboard.min.js"></script>
<script src="Oct13_session1_files/libs/quarto-html/tabby.min.js"></script>
<script src="Oct13_session1_files/libs/quarto-html/popper.min.js"></script>
<script src="Oct13_session1_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Oct13_session1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Oct13_session1_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Oct13_session1_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="3ie">
  <title>Reading DiD Results</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Oct13_session1_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Oct13_session1_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="Oct13_session1_files/libs/revealjs/dist/theme/quarto-eae8fb26e4df928de07c084d86b26716.css">
  <link href="Oct13_session1_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Oct13_session1_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Oct13_session1_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Oct13_session1_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="Oct13_session1_files/libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="Oct13_session1_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Reading DiD Results</h1>
  <p class="subtitle">Module 2 · Day 2, Session 1: Demystifying the Impact Analysis</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
3ie
</div>
</div>
</div>

</section>
<section id="what-this-session-gives-you" class="slide level2">
<h2>What this session gives you</h2>
<p>By the end of 90 minutes you will be able to:</p>
<div class="panel">
<ul>
<li>Explain what a difference-in-differences result means</li>
<li>Find the one number in an evaluation table that answers <strong>your</strong> question, and recognise the others which may be mistaken for it</li>
<li>Ask the critical question that decides whether the result can be trusted</li>
<li>Spot mistakes AI may make when interpreting an evaluation table</li>
</ul>
</div>
<p>You will see the analysis run, and we will talk through what each step is doing, to give a feel for what happens behind the scenes. You will not have to write or run any code yourself.</p>
<aside class="notes">
<p>0:00–0:02 · Set expectations. They are commissioners, not analysts. Their job is to interrogate evidence, not to produce it. We show the code and run it so they see where the numbers come from. Say plainly: “you will see how the analysis is done, but you will never have to write or run code yourself.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="compared-to-what-10-min" class="title-slide slide level1 center">
<h1>1 · Compared to what? <span class="mins">10 min</span></h1>

</section>
<section id="what-happened-to-the-businesses-that-got-it" class="slide level2">
<h2>What happened to the businesses that got it</h2>

<img data-src="Oct13_session1_files/figure-revealjs/unnamed-chunk-1-1.png" width="1600" class="r-stretch"><p>Costs fell by <strong>665 AED</strong>, a drop of <strong>46%</strong>.</p>
<aside class="notes">
<p>0:02 · Do not editorialise. Present it as an evaluator might present a headline finding, and let it look good.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="show-of-hands" class="slide level2">
<h2>Show of hands</h2>
<div class="ask">
<p>Based on this evidence, did the programme work?</p>
</div>
<aside class="notes">
<p>0:05 · Count the hands and write the number on the flipchart. Ask two people why. Do NOT move on until the room has committed; the next slide only works if they have.</p>
<p>If someone says “we can’t tell without a comparison”: excellent, name them and say you will prove them right in thirty seconds.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="now-we-add-the-businesses-that-did-not-receive-the-program" class="slide level2">
<h2>Now we add the businesses that did not receive the program</h2>

<img data-src="Oct13_session1_files/figure-revealjs/unnamed-chunk-2-1.png" width="1700" class="r-stretch"><aside class="notes">
<p>0:08 · Silence for a beat. Let them see the comparison line rising, then ask the same question again and watch the hands change. Then say it plainly: the comparison group’s costs rose too, so the honest effect is larger than the headline drop, not smaller. A comparison group is a correction, not a haircut, and it can go either way. We compute it exactly next.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-idea-in-four-numbers-13-min" class="title-slide slide level1 center">
<h1>2 · The idea, in four numbers <span class="mins">13 min</span></h1>

</section>
<section id="difference-in-differences-in-one-sentence" class="slide level2">
<h2>Difference-in-differences in one sentence</h2>
<div class="ask">
<p>Compare <strong>the change over time</strong> in the group that got the programme with <strong>the change over time</strong> in a group that did not.</p>
</div>
<p>The difference between those two changes is the estimated effect.</p>
<p>That is the central idea of this method.</p>
<aside class="notes">
<p>0:12 · Say the sentence, then say it again slowly. This is the sentence they should be able to repeat to a minister.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="when-is-difference-in-differences-the-right-tool" class="slide level2">
<h2>When is difference-in-differences the right tool?</h2>
<div class="panel">
<p><strong>Use it when you have:</strong> a group that received the programme and a group that did not, and an outcome measured <strong>before and after</strong> for both.</p>
</div>
<p>You reach for it when you could not randomise (the programme was already rolled out, or eligibility decided who got it), but you do have before-and-after data and a plausible comparison group.</p>
<aside class="notes">
<p>0:13 · Situate the method before the mechanics. DiD is the tool when you could not randomise but you do have before-and-after data on a treated group and a comparison group. Its power is not free: it buys causal leverage by assuming parallel trends, which Section 4 interrogates.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-did-and-not-something-simpler" class="slide level2">
<h2>Why DiD and not something simpler?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="warn">
<p><strong>Why not just before vs.&nbsp;after?</strong></p>
<p>Comparing the programme group with itself credits the programme with the <em>time trend</em>: the rising tide that would have moved costs anyway.</p>
</div>
</div><div class="column" style="width:50%;">
<div class="warn">
<p><strong>Why not just compare the two groups afterwards?</strong></p>
<p>A one-time snapshot credits the programme with the <em>baseline gap</em>: differences that were there before it started.</p>
</div>
</div></div>
<div class="ask">
<p>Difference-in-differences removes both. That is its whole job, which is why the two numbers it strips out are exactly the ones people may mistake for the effect.</p>
</div>
<aside class="notes">
<p>0:14 · This answers the closing question “why this method rather than another?”. Name the two things the simpler comparisons get wrong: they are exactly Trap 1 (the baseline gap) and Trap 2 (the time trend) in Section 3, so foreshadow them here.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="your-turn-fill-in-the-blanks" class="slide level2">
<h2>Your turn: fill in the blanks</h2>
<p>Difference-in-differences = (change for the offered group) − (change for the not-offered group)</p>
<div class="columns">
<div class="column" style="width:44%;">
<div class="panel">
<p><strong>First difference:</strong> each group’s change over time. This nets out fixed differences between the groups, but still contains the general time trend.</p>
<p><strong>Second difference:</strong> the difference between those two changes. This nets out the time trend and leaves the estimated effect.</p>
</div>
</div><div class="column" style="width:56%;">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="font-size: 22px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Before</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">After</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Offered</td>
<td style="text-align: right;">1,449</td>
<td style="text-align: right;">784</td>
<td style="text-align: right;">?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not offered</td>
<td style="text-align: right;">2,079</td>
<td style="text-align: right;">2,230</td>
<td style="text-align: right;">?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Difference of the changes</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">?</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
<div class="ask">
<p>Two subtractions, done in less than 2 minutes.</p>
</div>
<aside class="notes">
<p>0:15 · Hand out the four-numbers card. Ninety seconds of silence, genuinely silent, do not fill it. Walk the room. Most people get it, and that is the point: they own the method rather than receiving it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-answer" class="slide level2">
<h2>The answer</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="font-size: 26px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Before</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">After</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Offered</td>
<td style="text-align: right;">1,449</td>
<td style="text-align: right;">784</td>
<td style="text-align: right;">-665</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not offered</td>
<td style="text-align: right;">2,079</td>
<td style="text-align: right;">2,230</td>
<td style="text-align: right;">+151</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 241, 245, 1) !important;">Difference of the changes</td>
<td style="text-align: right; font-weight: bold; background-color: rgba(230, 241, 245, 1) !important;"></td>
<td style="text-align: right; font-weight: bold; background-color: rgba(230, 241, 245, 1) !important;"></td>
<td style="text-align: right; font-weight: bold; background-color: rgba(230, 241, 245, 1) !important;">-816</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="ask">
<p>-665 − (+151) = <strong>-816 AED</strong></p>
</div>
<aside class="notes">
<p>0:20 · “You have just estimated a causal effect with two subtractions.” When an evaluator shows you a difference-in-differences table, this is what is underneath it: no more than this.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="visualising-the-did" class="slide level2">
<h2>Visualising the DiD</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-label="1"></a><span class="co"># counterfactual for offered group</span></span>
<span id="cb1-2"><a href="" aria-label="2"></a>cf <span class="ot">&lt;-</span> off_b <span class="sc">+</span> ctl_chg</span>
<span id="cb1-3"><a href="" aria-label="3"></a></span>
<span id="cb1-4"><a href="" aria-label="4"></a><span class="fu">ggplot</span>(viz,</span>
<span id="cb1-5"><a href="" aria-label="5"></a>       <span class="fu">aes</span>(Time, Cost,</span>
<span id="cb1-6"><a href="" aria-label="6"></a>           <span class="at">colour =</span> Group,</span>
<span id="cb1-7"><a href="" aria-label="7"></a>           <span class="at">group =</span> Group)) <span class="sc">+</span></span>
<span id="cb1-8"><a href="" aria-label="8"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.4</span>) <span class="sc">+</span></span>
<span id="cb1-9"><a href="" aria-label="9"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb1-10"><a href="" aria-label="10"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>,</span>
<span id="cb1-11"><a href="" aria-label="11"></a>    <span class="at">x =</span> <span class="dv">1</span>, <span class="at">xend =</span> <span class="dv">2</span>,</span>
<span id="cb1-12"><a href="" aria-label="12"></a>    <span class="at">y =</span> off_b, <span class="at">yend =</span> cf,</span>
<span id="cb1-13"><a href="" aria-label="13"></a>    <span class="at">linetype =</span> <span class="st">"22"</span>,</span>
<span id="cb1-14"><a href="" aria-label="14"></a>    <span class="at">colour =</span> ACCENT) <span class="sc">+</span></span>
<span id="cb1-15"><a href="" aria-label="15"></a>  <span class="fu">annotate</span>(<span class="st">"label"</span>,</span>
<span id="cb1-16"><a href="" aria-label="16"></a>    <span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> (off_a <span class="sc">+</span> cf) <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb1-17"><a href="" aria-label="17"></a>    <span class="at">colour =</span> ALERT, <span class="at">label.size =</span> <span class="dv">0</span>,</span>
<span id="cb1-18"><a href="" aria-label="18"></a>    <span class="at">label =</span> <span class="fu">sprintf</span>(</span>
<span id="cb1-19"><a href="" aria-label="19"></a>      <span class="st">"DiD = %.0f AED"</span>, did_hand)) <span class="sc">+</span></span>
<span id="cb1-20"><a href="" aria-label="20"></a>  <span class="fu">scale_colour_manual</span>(</span>
<span id="cb1-21"><a href="" aria-label="21"></a>    <span class="at">values =</span> grp_cols) <span class="sc">+</span></span>
<span id="cb1-22"><a href="" aria-label="22"></a>  <span class="fu">theme_m2</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Oct13_session1_files/figure-revealjs/unnamed-chunk-6-1.png" width="1000"></p>
</figure>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>0:22 · The dotted line is the counterfactual, the invented number at the heart of every impact evaluation. It is never observed. Everything rests on how believable it is, which is exactly what Section 4 interrogates.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="implementing-and-interpreting-did-14-min" class="title-slide slide level1 center">
<h1>3 · Implementing and interpreting DiD <span class="mins">14 min</span></h1>

</section>
<section id="implementing-did-with-a-regression" class="slide level2">
<h2>Implementing DiD with a regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="" aria-label="1"></a><span class="co"># One regression recovers all four numbers at once.</span></span>
<span id="cb2-2"><a href="" aria-label="2"></a><span class="co"># The interaction term is the difference-in-differences.</span></span>
<span id="cb2-3"><a href="" aria-label="3"></a>out_did <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(</span>
<span id="cb2-4"><a href="" aria-label="4"></a>  waste_management_costs <span class="sc">~</span> round <span class="sc">*</span> enrolled,</span>
<span id="cb2-5"><a href="" aria-label="5"></a>  <span class="at">data     =</span> tn,                        <span class="co"># businesses in treatment neighbourhoods</span></span>
<span id="cb2-6"><a href="" aria-label="6"></a>  <span class="at">clusters =</span> neighborhood_identifier)   <span class="co"># cluster standard errors by neighbourhood</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="panel">
<ul>
<li><code>round</code>: time indicator, 0 before the programme and 1 after</li>
<li><code>enrolled</code>: group indicator, 1 offered the programme and 0 not offered</li>
<li><code>round:enrolled</code>: the interaction, which is the DiD effect</li>
</ul>
</div>
</section>
<section id="running-the-regression" class="slide level2">
<h2>Running the regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="" aria-label="1"></a>out_did <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(waste_management_costs <span class="sc">~</span> round <span class="sc">*</span> enrolled,</span>
<span id="cb3-2"><a href="" aria-label="2"></a>                     <span class="at">data =</span> tn, <span class="at">clusters =</span> neighborhood_identifier)</span>
<span id="cb3-3"><a href="" aria-label="3"></a></span>
<span id="cb3-4"><a href="" aria-label="4"></a><span class="fu">tibble</span>(<span class="at">term      =</span> <span class="fu">names</span>(<span class="fu">coef</span>(out_did)),</span>
<span id="cb3-5"><a href="" aria-label="5"></a>       <span class="at">estimate  =</span> <span class="fu">round</span>(<span class="fu">coef</span>(out_did), <span class="dv">1</span>),</span>
<span id="cb3-6"><a href="" aria-label="6"></a>       <span class="at">std.error =</span> <span class="fu">round</span>(out_did<span class="sc">$</span>std.error, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="" aria-label="7"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span> <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">font_size =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top" style="font-size: 20px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2079.1</td>
<td style="text-align: right;">17.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">round</td>
<td style="text-align: right;">151.3</td>
<td style="text-align: right;">36.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">enrolled</td>
<td style="text-align: right;">-630.2</td>
<td style="text-align: right;">19.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">round:enrolled</td>
<td style="text-align: right;">-816.3</td>
<td style="text-align: right;">32.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="ask">
<p>Three coefficients, only one is the programme’s effect. Which one?</p>
</div>
<aside class="notes">
<p>0:26 · Run the chunk live if you like, then take a vote across the three coefficients. Many will pick <code>enrolled</code> because it is large and has the word “enrolled” in it. That is the trap the next slides unpack.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trap-1-the-baseline-gap" class="slide level2">
<h2>Trap 1: the baseline gap</h2>
<div class="hero">
  <div class="value alert">-630</div>
  <div class="label"><code>enrolled</code>: how far apart the groups were BEFORE the programme</div>
</div>
<div class="warn">
<p>Businesses offered the programme already spent 630 AED less than those not offered. Nothing the programme did caused this. It predates the programme entirely.</p>
<p>Reporting it as an effect credits the programme with a difference it inherited.</p>
</div>
<aside class="notes">
<p>0:30 · This is not hypothetical. Ask whether anyone has seen a summary quote a baseline difference as an impact. Usually at least one person has.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="trap-2-the-time-trend" class="slide level2">
<h2>Trap 2: the time trend</h2>
<div class="hero">
  <div class="value alert">+151</div>
  <div class="label"><code>round</code>: what happened to the comparison group anyway</div>
</div>
<div class="panel">
<p>Costs rose 151 AED for businesses that received nothing. This is the rising tide: volumes, prices, regulation.</p>
<p>It is the thing difference-in-differences exists to strip out. It is not the effect.</p>
</div>
</section>
<section id="the-number-that-answers-your-question" class="slide level2">
<h2>The number that answers your question</h2>
<div class="hero">
  <div class="value">-816 AED</div>
  <div class="label"><code>round:enrolled</code>: the extra change in the programme group</div>
</div>
<div class="ask">
<p>You should be able to point to this row yourself: that is the skill this session builds.</p>
</div>
<p>It is the same number you calculated by hand.</p>
<aside class="notes">
<p>0:34 · Close the loop back to the four numbers. The regression is not a black box producing a mystery figure. It is their two subtractions, with a precision estimate attached.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-sure-are-we" class="slide level2">
<h2>How sure are we?</h2>

<img data-src="Oct13_session1_files/figure-revealjs/unnamed-chunk-9-1.png" width="1800" class="r-stretch"><div class="panel">
<p>The data are consistent with an effect anywhere in that range. For a decision, the useful question is not <em>“is it narrow?”</em> but:</p>
<p><strong>Does my decision change depending on where in this range the truth sits?</strong></p>
</div>
<aside class="notes">
<p>0:36 · The reframing that matters for commissioners. Statisticians ask about precision; decision-makers should ask about decision-relevance. Here the whole interval sits below the bar, so the imprecision does not change the call.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="significant-is-not-the-same-as-sufficient" class="slide level2">
<h2>Significant is not the same as sufficient</h2>
<div class="warn">
<p>The estimate is <strong>statistically significant</strong>: we are confident it is not zero.</p>
<p>It is also <strong>below the bar you set</strong>: it is not big enough to act on.</p>
<p>These are two different questions, and the table only answers the first.</p>
</div>
<aside class="notes">
<p>0:38 · The most transferable idea in the session. Flag that it returns in the AI exercise, because AI conflates the two almost every time.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-one-question-14-min" class="title-slide slide level1 center">
<h1>4 · The one question <span class="mins">14 min</span></h1>

</section>
<section id="were-the-two-groups-heading-the-same-way" class="slide level2">
<h2>Were the two groups heading the same way?</h2>
<p>Everything so far rests on one assumption:</p>
<div class="ask">
<p>Without the programme, the two groups’ costs would have moved in parallel.</p>
</div>
<p>That dotted counterfactual line is only believable if the comparison group is a fair stand-in for what the programme group would have done.</p>
<div class="panel">
<p>It cannot be proven. It can only be made more or less plausible.</p>
</div>
</section>
<section id="which-of-these-would-you-trust" class="slide level2">
<h2>Which of these would you trust?</h2>

<img data-src="Oct13_session1_files/figure-revealjs/unnamed-chunk-10-1.png" width="2000" class="r-stretch"><div class="warn">
<p>Only <strong>A</strong> supports the assumption. In <strong>B</strong> and <strong>C</strong> the gap was already moving, so some of what the method will call an effect was going to happen anyway.</p>
</div>
<aside class="notes">
<p>0:40 · Vote on each panel before explaining. Make them articulate why B and C are a problem. Someone usually spots that C would <em>understate</em> the effect while B would overstate it. Draw that out if it comes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="threats-to-the-parallel-trends-assumption" class="slide level2">
<h2>Threats to the parallel trends assumption</h2>
<div class="panel">
<ol type="1">
<li><strong>Differential shocks:</strong> something hits one group and not the other, such as another policy or a local price change.</li>
<li><strong>Compositional change:</strong> the make-up of a group shifts over time, through selective entry or attrition.</li>
<li><strong>Anticipation:</strong> behaviour changes before the programme starts, such as holding off spending to wait for the subsidy.</li>
<li><strong>Spillovers:</strong> the programme affects the comparison group too, which makes the effect look smaller.</li>
</ol>
</div>
<aside class="notes">
<p>0:42 · These are the ways the assumption breaks. Ask the room which is most likely for GreenWaste; anticipation and spillovers both come up.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="testing-for-parallel-pre-trends" class="slide level2">
<h2>Testing for parallel pre-trends</h2>
<p>When you have several periods <em>before</em> the programme, you plot the two groups and check they were already moving together.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="" aria-label="1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb4-2"><a href="" aria-label="2"></a>pre <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb4-3"><a href="" aria-label="3"></a>  <span class="at">period =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">unit =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,</span>
<span id="cb4-4"><a href="" aria-label="4"></a>  <span class="at">group =</span> <span class="fu">c</span>(<span class="st">"Comparison"</span>,</span>
<span id="cb4-5"><a href="" aria-label="5"></a>            <span class="st">"Programme"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="" aria-label="6"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="dv">10</span> <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> period <span class="sc">+</span></span>
<span id="cb4-7"><a href="" aria-label="7"></a>    <span class="fu">ifelse</span>(group <span class="sc">==</span> <span class="st">"Programme"</span> <span class="sc">&amp;</span></span>
<span id="cb4-8"><a href="" aria-label="8"></a>             period <span class="sc">&gt;</span> <span class="dv">2</span>,</span>
<span id="cb4-9"><a href="" aria-label="9"></a>           <span class="sc">-</span><span class="dv">3</span> <span class="sc">*</span> (period <span class="sc">-</span> <span class="dv">2</span>), <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb4-10"><a href="" aria-label="10"></a>    <span class="fu">rnorm</span>(<span class="fu">n</span>()))</span>
<span id="cb4-11"><a href="" aria-label="11"></a></span>
<span id="cb4-12"><a href="" aria-label="12"></a><span class="fu">ggplot</span>(pre,</span>
<span id="cb4-13"><a href="" aria-label="13"></a>       <span class="fu">aes</span>(period, y,</span>
<span id="cb4-14"><a href="" aria-label="14"></a>           <span class="at">colour =</span> group)) <span class="sc">+</span></span>
<span id="cb4-15"><a href="" aria-label="15"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean,</span>
<span id="cb4-16"><a href="" aria-label="16"></a>               <span class="at">geom =</span> <span class="st">"line"</span>) <span class="sc">+</span></span>
<span id="cb4-17"><a href="" aria-label="17"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">2.5</span>,</span>
<span id="cb4-18"><a href="" aria-label="18"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb4-19"><a href="" aria-label="19"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Period"</span>,</span>
<span id="cb4-20"><a href="" aria-label="20"></a>       <span class="at">y =</span> <span class="st">"Outcome"</span>) <span class="sc">+</span></span>
<span id="cb4-21"><a href="" aria-label="21"></a>  <span class="fu">theme_m2</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Oct13_session1_files/figure-revealjs/unnamed-chunk-12-1.png" width="1000"></p>
</figure>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>0:44 · Illustrative data, not GreenWaste. Point out that the groups move in parallel before the dashed line and only diverge after. Then contrast: GreenWaste has only one before-period, so this check is impossible here (next slide).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="so-were-they" class="slide level2">
<h2>So, were they?</h2>
<div class="warn">
<p>We measured costs at <strong>two points in time</strong>. Once before, once after.</p>
<p>To check whether the groups were already moving apart, you need at least <strong>two observations before</strong> the programme started.</p>
<p>We have one.</p>
</div>
<div class="ask">
<p>The parallel trends assumption cannot be tested with this data. Not “was not tested”: <strong>cannot be</strong>.</p>
</div>
<p>This is not unusual. It is the normal situation for most evaluations you will commission.</p>
<aside class="notes">
<p>0:46 · Do not soften this. The honest position is far more useful to them than the textbook one, and it sets up the AI failure in the next section directly.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="and-look-at-who-the-comparison-group-is" class="slide level2">
<h2>And look at who the comparison group is</h2>

<img data-src="Oct13_session1_files/figure-revealjs/unnamed-chunk-13-1.png" width="1900" class="r-stretch"><div class="warn">
<p>The two groups do not overlap <strong>at all</strong>. The comparison group is not “similar firms that happened to miss out”: it is, by construction, the better-scoring half of the market.</p>
</div>
<aside class="notes">
<p>0:48 · Let the picture do the work: two blocks of colour that never touch.</p>
<p>Then ask the killer question: “would you expect these two groups to move in parallel on their own?” The honest answer is that we have no particular reason to think so, and no way to check.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-to-ask-when-it-cannot-be-tested" class="slide level2">
<h2>What to ask when it cannot be tested</h2>
<p>You will rarely get a clean pre-trend check. Ask for the next best things:</p>
<div class="panel">
<ol type="1">
<li><strong>How was the comparison group chosen, and how are they different?</strong></li>
<li><strong>What else changed for one group and not the other?</strong> (other programmes, regulations, shocks)</li>
<li><strong>Did anyone change behaviour in anticipation of the programme?</strong></li>
<li><strong>Could the programme have affected the comparison group too?</strong> (spillovers make effects look smaller)</li>
<li><strong>What is the result with a different comparison group?</strong></li>
</ol>
</div>
<p>An evaluator with good answers to these has earned some trust. One who has not considered them has not.</p>
<aside class="notes">
<p>0:51 · These five are on the take-away card. Say that question 1 is the one that would have caught the problem on the previous slide, and it requires no statistics at all.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="ai-snapshot-18-min" class="title-slide slide level1 center">
<h1>5 · AI Snapshot <span class="mins">18 min</span></h1>

</section>
<section id="we-gave-ai-the-table-and-asked-it-to-explain" class="slide level2">
<h2>We gave AI the table and asked it to explain</h2>
<p><strong>Prompt:</strong> <em>“Explain these results.”</em></p>
<div class="ai-output">
<p>The analysis uses a difference-in-differences design to evaluate the GreenWaste Program. The results show a statistically significant treatment effect of −816.3 AED (<span class="flag">p &lt; 0.001</span>), indicating that the programme <span class="flag">increased savings</span> by 816 AED per business.</p>
<p>The model also shows that enrolled businesses spent 630 AED less at baseline and that costs rose 151 AED over the period, <span class="flag">both consistent with the programme’s expected effects</span>.</p>
<p><span class="flag">The parallel trends assumption was tested and holds</span>, confirming that the groups followed similar trajectories before the programme began. The estimate is therefore robust.</p>
<p><strong>Recommendation:</strong> <span class="flag">the programme is effective and should be scaled up nationally</span>.</p>
</div>
<div class="ask">
<p>Four things here are wrong. Three minutes: find them.</p>
</div>
<aside class="notes">
<p>0:53 · Hand out the printed copy. Three minutes in pairs, marking up the text. Take answers from the room before revealing. Someone almost always finds the scale-up recommendation first; the fabricated test is the one they miss.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-it-got-wrong" class="slide level2">
<h2>What it got wrong</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="warn">
<p><strong>1 · It invented a test that is impossible</strong></p>
<p>With two rounds of data there is nothing to test. The model produced a confident sentence about a check that was never run and could not be run.</p>
</div>
<div class="warn">
<p><strong>2 · It ignored your decision rule</strong></p>
<p>−816 is below the 1,000 AED bar. It read the result as significant and recommended national scale-up anyway.</p>
</div>
</div><div class="column" style="width:50%;">
<div class="warn">
<p><strong>3 · It called a pre-existing gap an effect</strong></p>
<p>The 630 AED baseline difference existed before the programme. Calling it “consistent with expected effects” credits the programme with it.</p>
</div>
<div class="warn">
<p><strong>4 · It invented precision</strong></p>
<p><code>p &lt; 0.001</code> appears nowhere in the table it was given. It was inferred from the asterisks and stated as fact.</p>
</div>
</div></div>
<aside class="notes">
<p>0:56 · Take them in order. Error 1 is the one groups almost never find on their own. Flag that, because it is the most dangerous.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="notice-what-they-have-in-common" class="slide level2">
<h2>Notice what they have in common</h2>
<div class="ask">
<p>The answer was fluent, confident and correctly formatted.</p>
</div>
<div class="warn">
<p>Nothing in its tone distinguishes the true sentences from the invented ones. There is no surface cue: no hedge, no hesitation, no change of register around the four things it made up.</p>
</div>
<div class="panel">
<p>This is what makes the failures dangerous in a briefing note: they read exactly like the parts that are right.</p>
</div>
<aside class="notes">
<p>0:58 · Land the meta-point hard. If they take one thing from the session about AI, it is this: fluency is not accuracy, and confidence is not a signal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-same-table-a-better-prompt" class="slide level2">
<h2>The same table, a better prompt</h2>
<div class="columns">
<div class="column" style="width:42%;">
<h3 id="what-people-type">What people type</h3>
<div class="panel">
<p><em>“Explain these results.”</em></p>
</div>
<ul>
<li>No decision rule</li>
<li>No context about the data</li>
<li>No invitation to flag uncertainty</li>
<li>Every gap filled with a confident guess</li>
</ul>
</div><div class="column" style="width:58%;">
<h3 id="what-to-type-instead">What to type instead</h3>
<div class="ask">
<p><em>I am a commissioner, not an analyst. Below is a difference-in-differences table from a waste-management programme evaluation. Our decision rule: the programme must cut costs by at least 1,000 AED per business to justify scale-up. The data has two rounds only.</em></p>
<p><em>Before answering, ask me any questions you need about how the comparison group was chosen.</em></p>
<p><em>Then: (1) which single number is the estimated effect, and which are not; (2) does it meet our rule; (3) what would have to be true for me to believe it, and which of those I cannot verify from this table.</em></p>
</div>
</div></div>
<aside class="notes">
<p>1:00 · Walk through what each element does. The highest-leverage single sentence is “ask me any questions you need before answering”: it converts the model from a guesser into an interviewer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="your-turn" class="slide level2">
<h2>Your turn</h2>
<div class="panel">
<p>In your groups, using the table on your handout:</p>
<ol type="1">
<li>Run the <strong>short prompt</strong>. Read what you get.</li>
<li>Run the <strong>full prompt card</strong>. Answer the questions it asks you.</li>
<li>Compare: what did the second answer add, remove, or hedge?</li>
<li>Paste the second answer into a <strong>fresh chat</strong> and ask: <em>“Review this interpretation for errors and overstatement.”</em></li>
</ol>
</div>
<div class="ask">
<p>Step 4 matters. A second, clean conversation catches what the first one is already committed to.</p>
</div>
<aside class="notes">
<p>1:02–1:10 · Eight minutes of group work. Circulate and collect one good example and one bad one for the debrief. If a group gets a genuinely new failure mode, screenshot it. It goes into the failures library for later sessions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="debrief" class="slide level2">
<h2>Debrief</h2>
<ul>
<li>What did AI <strong>overstate</strong>?</li>
<li>What did it <strong>soften</strong> or leave out?</li>
<li>Did it <strong>invent</strong> anything: a test, a number, a caveat?</li>
<li>Did the second chat catch what the first missed?</li>
</ul>
<div class="ask">
<p>Two habits: tell the AI your decision rule, and make it ask you questions before it answers.</p>
</div>
</section></section>
<section>
<section id="abu-dhabi-doh-15-min" class="title-slide slide level1 center">
<h1>6 · Abu Dhabi DOH <span class="mins">15 min</span></h1>
<!-- PLACEHOLDER: Abu Dhabi DOH health evaluation findings not yet received.
     Replace the three slides below with the real case. Keep the structure:
     (1) the case and the decision at stake
     (2) the table, read using the four steps from Section 3
     (3) the credibility question, using the five questions from Section 4   -->
</section>
<section id="placeholder-the-doh-evaluation" class="slide level2">
<h2><code>[PLACEHOLDER]</code> The DOH evaluation</h2>
<div class="warn">
<p><strong>Awaiting real findings.</strong> Structure is final; only the numbers and labels change.</p>
</div>
<div class="facts">
  <div class="k">Programme</div>      <div class="v">[to be inserted]</div>
  <div class="k">Outcome</div>        <div class="v">[to be inserted]</div>
  <div class="k">Comparison</div>     <div class="v">[to be inserted]</div>
  <div class="k">Decision</div>       <div class="v">[to be inserted]</div>
  <div class="k">Periods of data</div><div class="v">[note whether pre-trends can be checked]</div>
</div>
<aside class="notes">
<p>Ask Fiona specifically whether the DOH evaluation has more than one pre-period. If it does, this is the chance to show a real pre-trend check and complete the contrast with GreenWaste, which would make this section the strongest in the session rather than a repeat.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="placeholder-reading-the-doh-result" class="slide level2">
<h2><code>[PLACEHOLDER]</code> Reading the DOH result</h2>
<p>Apply the four steps, in order:</p>
<div class="panel">
<ol type="1">
<li>Which row is the difference-in-differences estimate?</li>
<li>What are the other coefficients telling you, which is the baseline gap?</li>
<li>What does the interval mean for <strong>this</strong> decision?</li>
<li>Does it clear the threshold that matters here?</li>
</ol>
</div>
<aside class="notes">
<p>Group exercise on the handout, not a lecture. Eight minutes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="placeholder-would-you-act-on-it" class="slide level2">
<h2><code>[PLACEHOLDER]</code> Would you act on it?</h2>
<div class="panel">
<ul>
<li>How was the comparison group chosen, and how are they different?</li>
<li>What else changed for one group and not the other?</li>
<li>Any anticipation effects?</li>
<li>Any spillovers onto the comparison group?</li>
<li>What happens with a different comparison group?</li>
</ul>
</div>
<div class="ask">
<p>Verdict round: act on it, act with caveats, or send it back?</p>
</div>
<aside class="notes">
<p>1:22 · Hands, not discussion. Keeps time. Note who says “send it back” and ask them for the one question that decided it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="closing-4-min" class="title-slide slide level1 center">
<h1>7 · Closing <span class="mins">4 min</span></h1>

</section>
<section id="three-questions-to-ask-any-evaluator-presenting-did" class="slide level2">
<h2>Three questions to ask any evaluator presenting DiD</h2>
<div class="panel">
<p><strong>1 · “Why difference-in-differences here rather than another method like a randomised trial?”</strong></p>
<p>A strong answer names what they could not do and what this design buys them. A weak one treats the method as the only option.</p>
</div>
<div class="panel">
<p><strong>2 · “Were the two groups already moving apart, and how do you know?”</strong></p>
<p>If they cannot test it, ask what they offer instead.</p>
</div>
<div class="panel">
<p><strong>3 · “Does this clear the bar we set, and what is the range?”</strong></p>
<p>Significant is not the same as sufficient.</p>
</div>
<aside class="notes">
<p>1:25 · The take-away card. Deliberately short enough to remember in a meeting without notes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-this-sits-day-2-scoreboard" class="slide level2">
<h2>Where this sits: Day 2 scoreboard</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top" style="font-size: 20px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 241, 245, 1) !important;">Difference-in-differences</td>
<td style="text-align: center; font-weight: bold; background-color: rgba(230, 241, 245, 1) !important;">-816 AED</td>
<td style="text-align: center; font-weight: bold; background-color: rgba(230, 241, 245, 1) !important;">Below the bar → do not scale</td>
</tr>
<tr class="even">
<td style="text-align: left;">Regression discontinuity</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">(this afternoon)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Matching</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">(this afternoon)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Randomised trial</td>
<td style="text-align: center;">-1,014 AED (Module 1)</td>
<td style="text-align: center;">Above the bar → scale up</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="ask">
<p>Same programme, same data, and the methods do not agree.</p>
</div>
<aside class="notes">
<p>1:27 · Tee up the tension deliberately. The disagreement between methods is Day 2’s real lesson, and it is what makes the afternoon worth attending.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-might-did-differ-from-the-randomised-result" class="slide level2">
<h2>Why might DiD differ from the randomised result?</h2>
<div class="warn">
<p>The randomised trial in Module 1 found a larger effect (−1,014 AED) and cleared the bar. DiD, on the same programme, did not. Why?</p>
<ul>
<li>Selection bias is not fully addressed by DiD</li>
<li>Non-enrolled industries may be on different trends</li>
<li>The parallel trends assumption may not hold</li>
</ul>
</div>
<aside class="notes">
<p>1:28 · The bridge to the afternoon. DiD and the RCT answer slightly different questions about slightly different businesses, so they can disagree even on the same data.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="next-session" class="slide level2">
<h2>Next session</h2>
<p><strong>Reading RDD Results</strong>: what happens when eligibility is decided by a cut-off, and why that gives you a different kind of evidence about a different group of businesses.</p>
<div class="panel">
<p>You have already seen the cut-off that matters: the efficiency index at 58. This morning it was a problem. This afternoon it becomes the tool.</p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Oct13_session1_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Oct13_session1_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Oct13_session1_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Oct13_session1_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Oct13_session1_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Oct13_session1_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Oct13_session1_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Oct13_session1_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Oct13_session1_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Oct13_session1_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>