"""Approved Day 3: 11/10/13 screens, 60/60/75 minutes."""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from trainer_code import annotate_deck
import re
from build_day2_decks import header,slide,ask,chunk,raw,hidden,demo,open_answer
ROOT=Path(__file__).resolve().parents[1]
def head(title,n):return header(title,n).replace('Day 2','Day 3').replace('day2_case.R','day3_case.R')
def choices(labels):return raw('<div data-choices>'+''.join(f'<button data-choice aria-pressed="false">{x}</button>' for x in labels)+'<p role="status" class="feedback"></p></div>')
def table(code):return chunk('html_out(html_table('+code+'))')
s1=head('Judge a value for money claim',1)
s1+=slide('A saving is not the whole decision',hidden("gw <- read.csv('evaluation_data_GreenWaste_simple.csv')\ncity <- subset(gw, setting == 'city')\njoined <- city$took_part == 1\nchange <- city$cost_after - city$cost_before\nsaving <- -(mean(change[joined]) - mean(change[!joined]))\nbenefits <- saving * sum(1 / 1.05^(2:6))\ncost <- 1800")+ask('What would you need beyond a saving estimate before approving spending?')+'Recall the comparison and its limits. Add one cost you would want included.',4,'No new method lecture. Retrieve the city DiD result; its causal interpretation remains uncertain. All costs and future-saving inputs today are fictional course assumptions. One trainer demo only, no participant coding.')
s1+=slide('Read the ratio claim',chunk("html_out(sprintf('<p class=\"big-number\">%.2f</p><p>Benefits divided by costs, under the model assumptions.</p>%s',ratio(),fiction))")+ask('Would this ratio justify approval?')+choices(['Approve','Ask first','Do not approve']),4,'Commit before opening assumptions. Local controls only; for room totals use course room poll configured to this question, hidden until close, or cards. A ratio above 1 means modelled benefits exceed included costs; it is not proof of cause or a complete approval rule.')
s1+=slide('Open what went into it',table('assumptions')+ask('Which inputs need evidence before we rely on them?'),5,'Each input has a source/status. The annual saving is an estimated extra change, not a guaranteed causal benefit. Cost 1800, five years, lag one year and rate 5% are assumptions, not programme records. This corrects the old model calling invented costs facts.')
s1+=slide('Read benefits and costs',chunk("html_out(sprintf('<div class=\"evidence-pair\"><div class=\"evidence\"><h3>Modelled benefits</h3><p class=\"big-number\">%s</p></div><div class=\"evidence\"><h3>Included cost</h3><p class=\"big-number\">%s</p></div></div><p class=\"caption\">AED per business, at today&apos;s value. Fictional assumptions.</p>',fmt(model$saving*pv_factor()),fmt(model$cost)))")+demo('round(benefits / cost, 2)')+ask('What does a ratio above 1 tell us about this model?'),5,'Predict before Run. Code divides the modelled benefit stream by cost. Benefits discounted over years 2 to 6 at 5%; no benefits year 1. Printed values rounded, actual calculation unrounded. Explain benefit-cost ratio in plain language; ask about source uncertainty separately.')
s1+=slide('A saving next year',chunk("html_out(sprintf('<div class=\"evidence-pair\"><div class=\"evidence\"><h3>Next year</h3><p class=\"big-number\">%s</p><p>AED saving assumed</p></div><div class=\"evidence\"><h3>At today&apos;s value</h3><button data-open=\"discount\" data-closed=\"Open today&apos;s value\" data-opened=\"Hide today&apos;s value\" aria-controls=\"discount\" aria-expanded=\"false\">Open today&apos;s value</button><div id=\"discount\" hidden><p class=\"big-number\">%s</p><p>AED, at a 5%% discount rate</p></div></div></div>%s',fmt(model$saving),fmt(model$saving/1.05),fiction))")+ask('Why might a later saving count for less today?'),5,'This illustrates one year, not the first modelled benefit (year 2). Explain timing, opportunity cost and uncertainty without a finance lesson. Discount rate is the rate used to express future amounts at today\'s value. Negative/alternative rates are outside this task.')
s1+=slide('What costs were left out?','The headline includes equipment delivery. A reviewer asks about:\n\n**Staff time, administration and businesses\' own time.**\n\n'+ask('What would you request before accepting the cost total?')+'Mark the missing costs on **Sheet 1**.',6,'Fictional excerpt. Avoid double counting: ask what was included already, whose costs the study counts, amounts and timing. Adding costs can change the ratio even if the saving estimate stays fixed.')
s1+=slide('Predict your scenario','Each group receives one **scenario card**.\n\nRead the change. Predict the ratio before seeing the answer.\n\nPost your card number and prediction above the A1 line.\n\n'+ask('What evidence would show whether your scenario is plausible?'),8,'Preserve cards 1 to 5 and eight allocations 1,2,3,4,5,1,2,3. One different setting per card. No repeated live code: all five results are computed from the same model and revealed next. Protect group prediction and reasons; calculators optional.')
s1+=slide('Put it on the ratio wall',chunk("html_out(paste0('<button data-open=\"scenario-results\" data-closed=\"Open scenario results\" data-opened=\"Hide scenario results\" aria-controls=\"scenario-results\" aria-expanded=\"false\">Open scenario results</button><div id=\"scenario-results\" hidden>',html_table(data.frame(Card=scenarios$card,Scenario=scenarios$name,Ratio=fmt(scenarios$value,2)),compact=TRUE),'</div>'))")+ask('Which cards fall below 1?'),7,'Groups put cards in the lower lane at the actual ratio, leaving predictions above. Retain Fiona\'s A1 design, regenerate headline marker with corrected model. Values below 1 are scenario conclusions under assumptions, not observed programme failures.')
s1+=slide('What could flip the decision?','Use **Sheet 2**. Write the assumption you would investigate first.\n\nState the evidence you need and how it could affect the decision.\n\n'+ask('Does the headline depend on a plausible saving lasting long enough?'),6,'Individual then pairs. Duration and decay matter, costs may be missing, benefit attribution unresolved. Ratio sensitivity helps find missing evidence; it cannot establish a scenario is realistic.')
s1+=slide('Repair an AI recommendation','Illustrative AI draft:\n\n"The ratio exceeds 1, so GreenWaste is proven to be good value. The savings will last five years. Approval is justified."\n\n'+ask('Which assurances go beyond the source?')+open_answer('cost-ai','Open feedback','The ratio exceeds 1 under stated assumptions. Five years is assumed; benefits and costs need evidence. An unconditional approval is unsupported.'),6,'Authored AI draft. Mark and repair on paper before reveal. Optional prompt asks for input sources, omitted costs and assumptions before a recommendation. No AI account required; verify claims against source.')
s1+=slide('Your question from memory',ask('What would you ask before accepting a value for money claim?')+'Close the sheets. Write your question and its purpose. Work alone.',4,'Independent close. Saving threshold and benefit-cost ratio are different questions; neither settles the other. Total 60 minutes.')

s2=head('Read a chart before trusting its story',2)
s2+=slide('Which picture would you use?',hidden("gw <- read.csv('evaluation_data_GreenWaste_simple.csv')\ntp <- subset(gw, setting == 'city' & took_part == 1)")+chunk("html_out(paste0('<div class=\"chart-pair\"><div><h3>A</h3>',bar_svg(0,FALSE),'</div><div><h3>B</h3>',bar_svg(700,FALSE),'</div></div><p class=\"caption\">Two draft charts of the same records. Labels are missing.</p>',fiction))")+ask('Can you choose responsibly without the labels?'),4,'Retrieve source and comparison questions. These are deliberately incomplete drafts; accepting either shape alone is premature. Commit a reason. No room poll needed; pairs or local cards. Next screen supplies values and scales.')
s2+=slide('Same values different axes',chunk("html_out(paste0('<div id=\"axis-charts\"><div data-variant>',bar_svg(700),'</div><div data-variant hidden>',bar_svg(0),'</div></div><button data-swap=\"axis-charts\">Change the axis start</button>',fiction))")+ask('Which impression changes, and which recorded values stay the same?'),6,'Predict before toggle. Truncated bar baseline starts at 700 versus 0; true mean values identical. Bars should ordinarily start at 0; a truncated axis needs explicit disclosure and a reason. This is descriptive before/after, not a causal effect chart. Keyboard button must not advance deck.')
s2+=slide('Mark up the chart','Use the printed chart on **Sheet 1**. Work alone first.\n\nCircle the units. Mark where the axis starts.\n\nUnderline who is compared and when.\n\n'+ask('What can this chart support on its own?'),7,'Chart is full axis, participant before/after. Ask for source, annual AED, period 12 months and no causal comparison. Distribution and uncertainty absent, so do not infer everyone gained. The worksheet also includes its descriptive source caption.')
s2+=slide('What an average hides',chunk("html_out(sprintf('<p class=\"distribution-mean\">Mean: %s tonnes</p><button data-open=\"distribution\" data-closed=\"Open the individual values\" data-opened=\"Hide the individual values\" aria-controls=\"distribution\" aria-expanded=\"false\">Open the individual values</button><div id=\"distribution\" hidden>%s</div>%s',fmt(mean(ten$landfill_before),1),distribution_svg(),fiction))")+ask('Does the mean describe most of these ten businesses?'),6,'Predict before revealing Day 1 ten actual landfill records. Nine below the mean; one at 46 tonnes. Dot stacking makes repeated values visible. This is a small teaching selection, not a representative city distribution or a programme effect.')
s2+=slide('A percentage of what?',chunk("html_out(sprintf('<div class=\"percentage-pair\"><div><h3>Change in total tonnes</h3><p>%s%%</p></div><div><h3>Mean business percentage</h3><p>%s%%</p></div></div>%s',fmt(percent_total,1),fmt(percent_average,1),fiction))")+demo("total_fall <- 100 * (1 - sum(tp$landfill_after) /\n  sum(tp$landfill_before))\nround(total_fall, 1)")+ask('Why can these percentages differ for the same businesses?'),7,'One trainer demo after prediction. Total percentage weights businesses by their starting tonnes; mean business percentage gives each business equal weight. All before tonnes are positive. Two valid different summaries; neither alone establishes cause. Shorten variableline if editorclips. No school-zone or pie-chart case.')
s2+=slide('Read an estimate and its interval',chunk("html_out(interval_svg('trial',reveal=TRUE))")+raw('<button data-open="interval-trial" data-closed="Open the interval" data-opened="Hide the interval" aria-controls="interval-trial" aria-expanded="false">Open the interval</button>')+ask('Does the pilot chart settle the minimum saving rule?'),6,'Predict before interval opens. Pilot lottery after 12 months, annual AED saving. Interval crosses 1000. Teach units, compared population and reported uncertainty; intervals do not account for every bias. Use the existing computed SVG, not a new hand-coded result.')
s2+=slide('Choose and repair','Pairs work on **Sheet 2**.\n\nRepair a chart caption that claims cause from a before/after fall.\n\nName the source, units, comparison and one limit.\n\n'+ask('Would a decision-maker understand what the chart actually shows?'),10,'Protect repair task. Accept explicit source title and reference to worksheetfigure. No drawing software or code. Repairing caption alone cannot supply missing causal comparison; say so.')
s2+=slide('Check an AI caption','Illustrative AI draft:\n\n"GreenWaste caused a fall of almost half in every business\'s landfill waste. The before/after chart proves the programme works."\n\n'+ask('Which words would you keep, qualify or remove?')+open_answer('chart-ai','Open feedback','The total fell by about half among participants. Every business is unsupported, and this descriptive comparison cannot establish cause.'),6,'Authored example applies to the total landfill result, not the cost bars. Participants verify source and denominator. Optional AI prompt asks it to describe visible evidence and missing context before recommending. No account required.')
s2+=slide('Defend your chart choice',ask('What can your repaired caption help a reader conclude?')+'Give one supported statement and one limit.\n\nPoint to the chart evidence while explaining.',4,'Pairs share a short defence. Require the actual values, comparison and denominator; accept different captions when faithful.')
s2+=slide('Your question from memory',ask('What would you check first in a chart from an evaluation report?')+'Close the sheet. Write the check and explain why it matters.',4,'Independent close. Scales and labels, averages, comparison and uncertainty. Total 60minutes.')

s3=head('Question the analyst',3)
s3+=slide('Would you sign this note?',hidden("gw <- read.csv('evaluation_data_GreenWaste_simple.csv')\npilot <- subset(gw, setting == 'pilot')")+chunk("html_out(paste0('<p class=\"lead\">',qa_note,'</p>',fiction))")+choices(['Sign off','With conditions','Request evidence']),4,'The fictional recommendation intentionally overclaims. No correctionyet; recordopeningdecision and reason onSheet1. Optional roompoll Beforephase, configuredforquestion, noMenti. NoAIforentryorclose.')
s3+=slide('Locate its evidence',table('method_rows')+ask('Which result did the note choose, and who does each result describe?'),5,'Rows express savings as positive so intervals sortedaccordingly. Pilot andmatchingpointsclear1000 butintervalsspanit; DiDandRDDshort. Samecityrecordsarenotindependentconfirmations; populationsdiffer. Avoid treating fourestimatesasvotes.')
s3+=slide('Choose three useful questions',chunk("html_out(paste0('<ol>',paste(sprintf('<li>%s</li>',read_questions),collapse=''),'</ol>'))")+ask('Which three questions would most affect your sign-off decision?'),6,'Use shortenedQA sheetfivequestions, eachrequiresrequested sourceevidence. Individualschoosefirst, thengroups. Full20questionbatteryretiredfrommainroute buthistoricalqa_checklist.Rretained.')
s3+=slide('Improve a vague question','A reviewer asks: **"Is the evidence robust?"**\n\nRewrite it to request a specific result or check.\n\n'+ask('What answer would help you decide, and what would count as evidence?')+open_answer('qa-question','Open an example','Show the estimate and interval for the analysis you planned to rely on. Does its conclusion change under reasonable alternative choices?'),5,'Do not demandthewordrobustness. Askwhatcouldalterdecision, plannedanalysis not fabricatedregisteredplan. This exampleisnot proofsuchplanexists.')
s3+=slide('Prepare for the clinic','Groups rank their questions. Choose a spokesperson.\n\nWrite the evidence requested, before asking.\n\nKeep one follow-up question ready.\n\n'+ask('Which answer would you keep pressing for?'),7,'Eightgroupssameworksheet; assignfocuscomparison/assumption/data/conclusionacrosstwo groups each ifneeded. Trainerusesfixedsourcebank inpack, neverinventfieldworkdocumentation. Participants mayaskoutsidebank; marknot supplied.')
s3+=slide('Take a break','Keep your questions ready.\n\nThe trainer returns as the analyst.',5,'Protectfive-minutebreak. Noextraanalysesduringbreak.')
s3+=slide('Ask the analyst','Ask one specific question per group.\n\nRecord the answer and its source on **Sheet 2**.\n\nFollow up when a claim has no supporting evidence.\n\n'+ask('Did the answer address the question you asked?'),14,'Source-backedanswerbankonly; answerfactfullybrieflythenaskwhichmissing evidence remains. Eachgrouponequestionandfollowup, about90seconds. Whereunknownexplicitnot supplied; avoidperformingcertainty. Nooldneighbourhoodlab.')
s3+=slide('Open one requested result','A reviewer asks whether the pilot settles the saving rule.\n\nPredict where the two interval limits sit.\n\n'+demo("fit <- lm(cost_after ~ took_part, data = pilot)\nlimits <- confint(fit)['took_part', ]\nsort(round(-unname(limits)))")+ask('How does this answer change the recommendation?'),6,'One trainerdemo. Outputsmall-to-large95%intervalinAEDannualsaving. SourcecanonicalpilotOLS; trueRCTbutnotuniversalreachorfullvalueformoney. Ifroomasksotherissuefirst, usepaperbankthenexplainthisintervalanswersoneprioritisedthresholdquestion. NoadditionalRunloops.')
s3+=slide('Score the answers','For each answer choose:\n\n**Supported / Partial / Unanswered**\n\nWrite the source or the evidence still missing.\n\n'+ask('Which answer deserves a supported rating?'),6,'Participants recognise strengthsaswellasweaknesses. Pilotdesignfileandintervalcanbe supported; fieldworkquestionunanswered; allmethodsagreeisunsupported. Banktruthfuladmissionofmissingdataanswerswhatissuppliedbutdoesnotresolvequality.')
s3+=slide('Identify what remains',ask('Which unresolved issue could most change your decision?')+'Write the missing evidence and what you would do with it.\n\nAvoid an undirected list of concerns.',5,'Individualthenpairs. Requestearliertrends, localcredibility, poor matchsupport, fieldworkrecords, thresholdcertainty, generalisabilityorcostonbasisofclearreason. Do notinfermissingrecordsfromcompletegeneratedfile.')
s3+=slide('Revisit sign-off',choices(['Sign off','With conditions','Request evidence'])+ask('Which evidence changed your reason, or kept it the same?')+'Write your final decision before comparing with your opening choice.',5,'OptionalroompollAfterphase, closebeforetotals. Compare reasons notwinningvote. Differentprovisionaldecisionsneedclearlimits. Writtenevidenceislearningassessment.')
s3+=slide('Check an AI review','Illustrative AI draft:\n\n"There are four independent studies. All intervals clear the saving rule. No businesses are missing, so data quality is established."\n\n'+ask('Which statements would you correct using the source?')+open_answer('qa-ai','Open feedback','City methods share records and differ in reach. Two intervals span the rule and two fall short. A complete synthetic file does not establish fieldwork quality.'),4,'Authoredsnapshot; participantmarksupsourceonSheet2. NoexternalAIrequired. Optionalpromptasksclaim-to-sourceauditandunansweredevidencequestions.')
s3+=slide('Your request to the evaluator',ask('What specific evidence should the evaluator send next?')+'Write a short request and explain how it would affect your decision. Work alone.',3,'IndependentclosewithoutAI. Useindividualrequestsasreadiness evidence: comparison, resultuncertainty, limitationanddecisionrelevantquestion. Total75minutes.')
clinic_notes=[
 'The fictional note intentionally overclaims. Record the opening decision and reason before feedback. Optional course room poll with Before phase and hidden totals; no AI for this task.',
 'Savings are positive and interval endpoints sorted. Pilot and matching intervals span the rule; DiD and RDD fall short. City methods share records and describe different comparisons. Four estimates are not four votes.',
 'Use the five-question QA sheet. Each question must request specific evidence. Individuals choose first, then groups. The full historical question battery is outside the teaching route.',
 'Ask for a result or check that could change the decision. The example requests the planned analysis; it does not establish that a documented plan exists here.',
 'Eight groups rank questions. Assign comparison, assumptions, data and conclusions as focus areas if helpful. Use the fixed answer bank; say evidence is not supplied when it is absent.',
 'Protect the five-minute break. Keep the questions ready and do not add extra analyses.',
 'Allow one question and follow-up per group, about ninety seconds each. Answer briefly from the source bank. Ask which evidence is still missing; never invent fieldwork documentation.',
 'One trainer demonstration. Output gives the lower and upper 95% interval limits for annual saving in AED. This answers the threshold question; paper answers serve other questions. The pilot cannot establish nationwide reach or full value for money.',
 'Recognise strengths as well as missing evidence. The stated pilot comparison and interval are supported; fieldwork quality remains unanswered. Transparent disclosure does not itself resolve the concern.',
 'Work alone then in pairs. Choose a concrete evidence request and explain its decision relevance. Complete generated rows do not establish complete real-world follow-up.',
 'Optional room poll After phase: close before showing totals. Compare reasons, not a winning vote. Assess written evidence of reading. Different provisional decisions need clear limits.',
 'Authored AI draft, not a captured response. Correct claims using the result table and answer sources. No external AI account is required.',
 'Independent close without AI. Look for a specific source request, its purpose and how it could affect the recommendation. Total 75 minutes.'
]
iterator=iter(clinic_notes)
s3=re.sub(r'::: \{\.notes\}\n(\d+ minutes\.).*?\n:::',lambda m:'::: {.notes}\n'+m[1]+' '+next(iterator)+'\n:::',s3,flags=re.S)
for name,text in [('Oct14_session1_live.qmd',s1),('Oct14_session2.qmd',s2),('Oct14_session3_live.qmd',s3)]:
    (ROOT/name).write_text(annotate_deck(text).rstrip()+'\n',encoding='utf-8');print(name,text.count('## '),'content screens')
