"""Build the approved 60/60/75-minute reading route, using shared computed values."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def header(title,n):
    return f'''---
title: "{title}"
subtitle: "Module 2 | Day 2 | Session {n}"
author: "3ie"
always_allow_html: true
format:
  live-revealjs:
    theme: [theme_dge.scss, theme_live.scss, theme_reader.scss]
    logo: assets/dge_logo_horizontal.svg
    slide-number: true
    width: 1280
    height: 720
    slide-level: 2
    embed-resources: true
    include-after-body: _reader_interactions.html
webr:
  render-df: kable
  resources:
    - evaluation_data_GreenWaste_simple.csv
knitr:
  opts_chunk:
    echo: false
    warning: false
    message: false
---

{{{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}}}

```{{r setup, include=FALSE}}
source('day2_case.R')
```

'''
def slide(title,body,minutes,note):
    return f'## {title} {{.reader-slide}}\n\n{body}\n\n::: {{.notes}}\n{minutes} minutes. {note}\n:::\n\n'
def ask(text):return f'::: {{.ask}}\n{text}\n:::\n'
def chunk(code):return "```{r, results='asis'}\n"+code+"\n```\n"
def raw(code):return '```{=html}\n'+code+'\n```\n'
def hidden(code):return '```{webr}\n#| context: setup\n#| autorun: true\n#| echo: false\n#| include: false\n'+code+'\n```\n'
def demo(code):return '```{webr}\n#| echo: true\n#| autorun: false\n'+code+'\n```\n'
def result(method):
    return chunk(f"html_out(paste0(as.character(knitr::kable(report_row('{method}'),format='html',row.names=FALSE,table.attr='class=\"reading-table\"')),fiction))")
def open_answer(id,label,answer):
    return raw(f'<button data-open="{id}" data-closed="{label}" data-opened="Hide feedback" aria-controls="{id}" aria-expanded="false">{label}</button><div id="{id}" class="feedback" hidden>{answer}</div>')
def ai(claims,feedback):
    buttons=''.join(f'<button data-claim="{"unsupported" if wrong else "supported"}" aria-pressed="false">{text}</button>' for text,wrong in claims)
    return raw(f'<div class="claim-list">{buttons}</div><button data-check>Check selected claims</button><p data-feedback class="feedback" role="status"></p>')+f'\n<!-- feedback supplied on the section -->\n'

s1=header('Read the extra change',1)
s1+=slide('A question from yesterday',hidden("gw <- read.csv('evaluation_data_GreenWaste_simple.csv')\ncity <- subset(gw, setting == 'city')\nchange <- city$cost_after - city$cost_before\njoined <- city$took_part == 1")+ask('What comparison would help us read a fall in costs?')+'Tell a partner. Today we compare **changes in two groups**.',3,'Retrieve yesterday\'s question. No AI or definitions first. GreenWaste is fictional; city participants score 58 or below. Warm up webR before class. No participant coding.')
s1+=slide('Two groups over time',chunk("html_out(sprintf('<div class=\"evidence-pair\"><div class=\"evidence\"><h3>Took part</h3><p class=\"big-number\">%s &rarr; %s</p></div><div class=\"evidence\"><h3>Did not take part</h3><p class=\"big-number\">%s &rarr; %s</p></div></div><p class=\"caption\">Mean annual waste cost, AED. Before &rarr; 12 months later.</p>%s',fmt(means[1]),fmt(means[2]),fmt(means[3]),fmt(means[4]),fiction))")+ask('Which change should we subtract from which?'),4,'Take predictions before showing the calculation. Different starting levels alone do not rule out DiD; different untreated trends do.')
s1+=slide('Complete the four numbers', 'Use **Sheet 1**. Work alone, then compare with your group.\n\n1. Change among participants: after minus before.\n2. Change in the comparison group: after minus before.\n3. Extra change: first answer minus second answer.\n\n'+open_answer('did-arithmetic','Open the calculation','Extra change = participants\' change minus comparison change. Negative means lower costs.'),8,'Fiona\'s four-number task remains. Collect signs and units before feedback. Printed means are rounded; a one-AED discrepancy is acceptable. Use actual values for the final estimate.')
s1+=slide('Read the result row',result('did')+ask('Does this show an annual saving of at least `r fmt(decision_rule)` AED?')+demo("round(mean(change[joined]) - mean(change[!joined]))"),5,'One trainer calculation, prediction before Run. Output is the same coefficient as the regression in the printed extract. 95% interval uses business-clustered robust standard errors. The estimate and interval are short of the rule. This does not yet settle causal credibility.')
s1+=slide('What has to be true?', '<div class="lead">Without GreenWaste, the two groups would have changed in similar ways.</div>\n\nReports call this **parallel trends**.\n\n'+ask('What could make their changes differ even without GreenWaste?')+'Suggest one concrete reason.',6,'Examples: different price shocks, business mix changing, another policy affecting one group. The assumption concerns unobserved change without the programme; it does not require identical levels.')
s1+=slide('Would you trust these pictures?',chunk("html_out(paste0('<div class=\"trend-options\"><div><h3>A</h3>',trend_svg(1),'</div><div><h3>B</h3>',trend_svg(2),'</div></div><p class=\"caption\">Hypothetical pictures before a programme. These are not extra GreenWaste data.</p>'))")+ask('Which picture raises more concern? What if the comparison group changes?')+open_answer('trend-feedback','Open feedback','B was already changing differently. A is reassuring evidence, though it cannot prove future parallel trends. A changing mix of businesses can also mislead.'),8,'Give each pair a picture to explain. Both axes use the same invented scale. Picture A shows similar changes at different levels; B shows diverging changes. Ask about a comparator losing its larger businesses. No significance test establishes the assumption.')
s1+=slide('What cannot be checked here?', '<div class="big-number">One before period</div>\n\nThe GreenWaste file has one measure before and one after.\n\n'+ask('Can this file show whether earlier trends were similar?')+open_answer('pretrend-feedback','Open the limit','No. Ask for several earlier measures and an explanation of other changes affecting the groups.'),5,'The earlier pre-trend test was misleading with only one before period. State the data limit explicitly. Even several earlier periods cannot prove the unobserved post-programme trend.')
s1+=slide('Mark up the report extract','Open **Sheet 2**. Read alone before comparing with a partner.\n\nCircle the result and its units.\n\nUnderline the assumption.\n\nWrite one question that could change your decision.\n\n'+ask('What does the extract support, and what remains uncertain?'),10,'Protect the reading time. Ask participants to distinguish the estimated extra fall from an established causal saving. The printed extract names two periods and the parallel-trends assumption, and admits earlier trends cannot be checked.')
s1+=slide('Repair an AI claim', '<div class="lead">Illustrative AI draft</div>\n\n"The extra fall proves GreenWaste caused the saving. Parallel trends is satisfied. Scale-up meets the decision rule."\n\n'+ask('Which claims can you support from the extract?')+open_answer('did-ai','Open feedback','The estimated extra fall is supported. Cause requires a credible assumption; the file cannot check earlier trends. The result is below the saving rule.'),7,'Authored example, not a captured live AI response. Participants cross out unsupported claims on Sheet 2 and rewrite. Optional prompt: identify the comparison, assumption and missing evidence; ask me questions before concluding. Check any AI response against the source yourselves.')
s1+=slide('Your question for the evaluator',ask('What would you ask, and how could the answer change your decision?')+'Close the sheets. Write one question and its purpose. Work alone.\n\n**Difference-in-differences:** compare the changes, then question the assumption.',4,'Independent close, no AI. Collect a few questions about earlier trends, competing changes or stable group composition. Total 60 minutes.')

s2=header('Read the jump at a score rule',2)
s2+=slide('Who is compared?',hidden("gw <- read.csv('evaluation_data_GreenWaste_simple.csv')\ncity <- subset(gw, setting == 'city')\nnear <- subset(city, abs(score - 58) <= 2)\nnear$below <- as.integer(near$score <= 58)\nnear$distance <- near$score - 58")+raw('<div class="score-rule"><div>Score 58 or below<br><strong>Took part</strong></div><div>Score above 58<br><strong>Did not take part</strong></div></div>')+'Compare businesses **close to 58**, after 12 months.\n\n'+ask('Why might neighbours either side make a useful comparison?'),4,'Name the score rule and nearby comparison. Regression discontinuity, or RDD, is the report term. The corrected fictional data now follow the displayed rule exactly. Avoid claiming proximity alone makes assignment random.')
s2+=slide('Predict the jump',ask('Would costs be lower just below 58? By how much?')+raw('<div data-choices><button data-choice aria-pressed="false">Little difference</button><button data-choice aria-pressed="false">At least 1,000 AED lower</button><button data-choice aria-pressed="false">Need evidence</button><p class="feedback" role="status"></p></div>')+'Commit before opening the group card.',4,'Local choices only; use course-owned room poll for room totals or labelled cards. No estimate on this screen. Explain below-minus-above sign if needed.')
s2+=slide('Read your six businesses on each side','Each group has a different **Card A to H**.\n\nFind the mean cost on each side.\n\nSubtract: **at or below 58 minus above 58**.\n\nWrite the difference and your card letter on a sticky note.\n\n'+ask('What does your small sample suggest?'),10,'Preserve Fiona\'s seeds A4 B11 C37 D22 E9 F21 G33 H5. Each has six businesses per side, costs rounded to ten AED. Give one different card per group and calculators. A small-sample gap is a rough exercise result, not the regression jump.')
s2+=slide('Place your result on the wall','Put your sticky note on the **A1 number line**.\n\nLook for results far apart and a result with the opposite sign.\n\n'+ask('Why did the groups reach different answers?'),6,'One reporter per group. Cards sample different businesses, so costs and slopes vary. H may point in the other direction; use the generated key rather than memorised values. Draw the regression estimate and interval below the line on the next screen.')
s2+=slide('Read the reported jump',result('rdd')+demo("fit <- lm(cost_after ~ below * distance, data = near)\nround(coef(fit)['below'])")+ask('Which businesses does this result describe?'),5,'One trainer demo after prediction. OLS and robust regression coefficients agree; the printed 95% interval uses estimatr HC2, consistently from greenwaste_case.R. Regression allows a slope on each side. Estimate is local near 58, not the whole city. Mark estimate/interval on wall and compare the saving rule.')
s2+=slide('How close did they look?',chunk("html_out(sprintf('<div class=\"evidence-pair\"><div class=\"evidence\"><h3>Within 2 points</h3><p class=\"big-number\">%s</p><p>AED estimated jump</p></div><div class=\"evidence\"><h3>Within 5 points</h3><button data-open=\"wider-window\" data-closed=\"Open wider result\" data-opened=\"Hide wider result\" aria-controls=\"wider-window\" aria-expanded=\"false\">Open wider result</button><div id=\"wider-window\" hidden><p class=\"big-number\">%s</p><p>AED estimated jump</p></div></div></div>%s',fmt(rdd[1]),fmt(case$rdd5[1]),fiction))")+ask('Does a wider window change the decision against the rule?'),5,'Predict before opening. Bandwidth means how far either side the evaluator looked. Both displayed point estimates are below the rule. Stability alone does not remove other discontinuities; omit full sweep, placebo lab and sliders.')
s2+=slide('Something else jumps',ask('What if managers just below the line are younger?')+chunk("html_out(sprintf('<button data-open=\"age-jump\" data-closed=\"Open the age check\" data-opened=\"Hide the age check\" aria-controls=\"age-jump\" aria-expanded=\"false\">Open the age check</button><div id=\"age-jump\" hidden><p class=\"big-number\">%s years younger</p><p>Estimated age jump at 58, using a five-point window.</p></div>%s',fmt(abs(case$age_jump),1),fiction))"),7,'Prediction, then reveal. Pre-programme manager age jumps at the same line. It offers another possible explanation for a cost jump. Adjusting for age does not automatically rescue the causal interpretation. Ask the evaluator to investigate how the score rule and age discontinuity arose.')
s2+=slide('A short credibility check','On **Sheet 2**, mark each check as supported, concern or unknown.\n\n- Did the score rule determine participation?\n- Are the compared businesses close to 58?\n- Does something else jump at the line?\n- Who could this result apply to?\n\n'+ask('Which check would most affect your decision?'),9,'Rule followed in generated data, width two points disclosed, manager-age discontinuity is a concern, result local. Sorting/manipulation checks have not been supplied in this shortened extract: ask for them, do not invent a pass. Work alone then in pairs.')
s2+=slide('Check the AI recommendation','Illustrative AI draft:\n\n"The score rule proves GreenWaste saves money for every city business. The result justifies extending it to all eligible businesses."\n\n'+ask('Where does this recommendation go beyond the evidence?')+open_answer('rdd-ai','Open feedback','The estimate describes businesses near 58. A manager-age jump weakens its causal interpretation. The estimated saving is below the rule.'),6,'Repair on paper, verify locally. Optional AI prompt: name the compared businesses, another possible explanation and the missing evidence; ask me questions first. Do not use an AI verdict as the credibility check.')
s2+=slide('Your next question',ask('What would you ask before accepting this jump as an effect?')+'Close the sheets. Write your question and why the answer matters.\n\n**Regression discontinuity:** read the rule, the local comparison and what else jumps.',4,'Independent exit. Prefer specific next evidence about score setting, age, manipulation or reach. Total 60 minutes.')

s3=header('Read a matched comparison',3)
s3+=slide('What would make a fair comparison?',hidden("gw <- read.csv('evaluation_data_GreenWaste_simple.csv')\ncity <- subset(gw, setting == 'city')\nvars <- c('manager_age','staff','area','filtration')\nX <- scale(city[,vars])\nids <- which(city$took_part == 1)\ncontrols <- which(city$took_part == 0)\nXc <- t(X[controls,,drop=FALSE])\nmatched_difference <- function() {\n twins <- controls[vapply(ids,function(i) which.min(colSums((Xc-X[i,])^2)),1L)]\n mean(city$cost_after[ids]-city$cost_after[twins])\n}")+ask('Which business would you compare with a participant?')+'Choose on characteristics recorded **before GreenWaste**.',4,'Retrieve comparison question. Matching creates a comparison from observed characteristics; it does not create random assignment. No coding by participants; hidden helper prepares short trainer demonstration.')
s3+=slide('Read the profiles',raw('<div class="evidence-pair"><div class="evidence"><h3>Business A</h3><p>Manager age: 45<br>Size: small<br>Took part</p></div><div class="evidence"><h3>Business 2</h3><p>Manager age: 46<br>Size: small<br>Did not take part</p></div></div>')+ask('Would you pair these businesses? What is still unknown?')+'These profiles are invented for the exercise.',5,'Show profile fronts only, no costs. Age and size make a plausible pair on two observed features. Other important influences can differ. Do not call them identical.')
s3+=slide('Find the twins','Lay out your **seven profile cards**.\n\nPair A, B and C with their closest comparison profiles.\n\nUse manager age and size. Leave costs closed.\n\nRecord your pairs on **Sheet 1**.\n\n'+ask('Which comparison business is left over?'),12,'Preserve Fiona\'s A45small B38large C52small; 1=39large 2=46small 3=51small 4=29large. Cost slips separately held until next screen. Optional walking version: seven volunteers, eighth group checks. Intended A2 B1 C3; 4 unused. This toy activity differs from full-data matching which allows reuse and matches every participant.')
s3+=slide('Open the costs','Keep your pairs. The trainer now hands out the **cost slips**.\n\nFor each pair: participant cost minus comparison cost.\n\nFind the mean of the three differences.\n\n'+ask('Does this small exercise establish what GreenWaste caused?'),5,'Toy differences -1000,-900,-1100, average -1000. Invented exercise, not the full-city estimate. Unmeasured differences could explain some gap. Do not let groups rematch based on outcomes. Business4 unused in toy; this is not an excluded participant.')
s3+=slide('Read the matched result',result('match')+chunk("html_out(sprintf('<p>%s participants matched to %s different comparison businesses. Some comparison businesses were used more than once.</p>%s',fmt(sum(took)),fmt(match_A$used),fiction))")+ask('Does finding a match for everyone make every match convincing?'),6,'Full estimator: one nearest neighbour per participant, standardised characteristics, with replacement, no caliper or exclusions. Interval clusters by original business ID to allow reused controls, treating selected matches as given; it does not account fully for the match-selection procedure. Teach reported uncertainty and bias separately. All participants matched is true; closeness/support remains a question.')
s3+=slide('What was used to match?', '**Manager age, staff, premises area and filtration**, measured before the programme.\n\n'+demo('round(matched_difference())')+ask('What should the report show about the resulting pairs?'),5,'Predict sign before one trainer Run. Hidden helper does the same nearest-neighbour calculation as shared source; visible result reproduces the matched coefficient. Ask for similarity, poor matches and control reuse. Standardised distance gives measured variables a common scale. No coding mechanics lesson.')
s3+=slide('Take a break','Leave your sheets and cards on the table.\n\nWe return to one question: **what might matching have missed?**',5,'Protect five-minute break. Keep outputs hidden until participants return.')
s3+=slide('Leave out manager age',chunk("html_out(sprintf('<div class=\"evidence-pair\"><div class=\"evidence\"><h3>Four characteristics</h3><p class=\"big-number\">%s</p><p>AED matched difference</p></div><div class=\"evidence\"><h3>Age left out</h3><button data-open=\"omit-age\" data-closed=\"Open the result\" data-opened=\"Hide the result\" aria-controls=\"omit-age\" aria-expanded=\"false\">Open the result</button><div id=\"omit-age\" hidden><p class=\"big-number\">%s</p><p>AED matched difference</p></div></div></div>%s',fmt(match_A$est),fmt(match_B$est),fiction))")+ask('Why could leaving one characteristic out change the answer?'),6,'Predict direction before reveal. Same city, same algorithm, age excluded. The result is sensitive to information available. The three-feature match can look balanced on its own variables while ages and pre-programme costs differ. No repeated live runs.')
s3+=slide('What has not been measured?',ask('Could motivation affect both joining and waste costs?')+'A matched comparison can miss influences absent from its records.\n\n'+open_answer('unmeasured','Open the implication','Similar recorded characteristics do not rule out an unmeasured reason for the cost difference.'),5,'Motivation is a hypothetical omitted influence, not an observed column or established cause here. Balance concerns measured features; no balance table establishes absence of all bias.')
s3+=slide('Mark up the report extract','Read **Sheet 2** alone, then with a partner.\n\nCircle the result and interval.\n\nUnderline what was used to match.\n\nFlag one missing check and write your next question.\n\n'+ask('Which part of the conclusion needs more evidence?'),8,'Extract accurately discloses all participants matched, reuse, no maximum acceptable distance, and missing unmeasured-influence evidence. Ask for distances and poor support, baseline outcomes and sensitivity. Avoid saying all observed variables are perfectly balanced; manager age remains somewhat imbalanced.')
s3+=slide('Make a provisional judgement',ask('Would you act, act with conditions or request more evidence?')+'Write two sentences: your reason and the evidence that could change it.\n\nCompare with a partner. Different decisions need clear support.',6,'Protect individual judgement before discussion. Matching point estimate near rule, interval straddles rule. Causal credibility and programme costs still uncertain. Compare to pilot only if needed, no second case.')
s3+=slide('Check an AI assurance','Illustrative AI draft:\n\n"Every participant has a match, so selection bias is removed. The estimated saving guarantees the minimum saving rule is met."\n\n'+ask('What would you keep, cross out and rewrite?')+open_answer('match-ai','Open feedback','Every participant was matched. That fact does not remove all selection bias. The interval spans the decision rule, so reaching it is uncertain.'),5,'All participants matched is true in this algorithm. Unsupported inference is bias removed and threshold guaranteed. Optional AI prompt asks for claims and source evidence plus missing checks; ask questions before concluding. Verify with extract, no external AI required.')
s3+=slide('A question from memory',ask('What would you ask the evaluator about these matches?')+'Close your sheets. Write one question and explain its purpose.\n\n**Matching:** inspect what made the pairs similar, what was left out and who was reused.',3,'Individual exit, no AI. Look for concrete requests about closeness, reuse, baseline outcomes or unmeasured influences. Total 75 minutes.')
if __name__=='__main__':
    for name,text in [('Oct13_session1.qmd',s1),('Oct13_session2_live.qmd',s2),('Oct13_session3.qmd',s3)]:
        (ROOT/name).write_text(text.rstrip()+'\n',encoding='utf-8')
        print(name,'content screens',text.count('## '))
